# Generated by Django 5.1.6 on 2025-02-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='password',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
