# Generated by Django 5.1.6 on 2025-02-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_baseuser_email_alter_baseuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='accessToken',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
