# Generated by Django 5.1.6 on 2025-02-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_baseuser_accesstoken_baseuser_refreshtoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='accessToken',
        ),
    ]
