# Generated by Django 5.1.6 on 2025-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_baseuser_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
