# Generated by Django 5.1.6 on 2025-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_baseuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
