# Generated by Django 5.1.6 on 2025-03-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_baseuser_is_active_baseuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='user_permissions',
        ),
    ]
