# Generated by Django 5.1.6 on 2025-02-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='coin',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
