# Generated by Django 5.1.6 on 2025-02-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_coin_icon_url_coin_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='icon',
        ),
    ]
