# Generated by Django 5.1.6 on 2025-02-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_coin_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='url_logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
