# Generated by Django 5.1.6 on 2025-02-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_coin_url_logo'),
        ('userauth', '0007_baseuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('reserved_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('breakeven_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.baseuser')),
            ],
            options={
                'unique_together': {('user', 'coin')},
            },
        ),
    ]
