# Generated by Django 5.1.6 on 2025-03-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_spotbalance_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spotbalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='spotbalance',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='spotbalance',
            name='user',
        ),
        migrations.DeleteModel(
            name='FutureBalance',
        ),
        migrations.DeleteModel(
            name='SpotBalance',
        ),
    ]
