# Generated by Django 5.1.6 on 2025-03-12 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_spotbalance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('reserved_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('breakeven_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'coin')},
            },
        ),
    ]
