# Generated by Django 5.1.6 on 2025-03-29 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_totalbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TradeFiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_currency', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TradePaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradeCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trades30d', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('limit_min', models.IntegerField(default=0)),
                ('limit_max', models.IntegerField(default=0)),
                ('toCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.tradecryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fromCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.tradefiatcurrency')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.tradepaymentmethods')),
            ],
        ),
    ]
