# Generated by Django 5.1.6 on 2025-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_tradecryptocurrency_tradefiatcurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecurrency',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=5),
        ),
    ]
