# Generated by Django 5.1.6 on 2025-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_tradecurrency_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradecurrency',
            name='welcome_message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
