# Generated by Django 5.1.6 on 2025-04-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_tradecurrency_welcome_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('currency_type', models.CharField(choices=[('FIAT', 'fiat'), ('CRYPTO', 'crypto')], max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='tradecurrency',
            name='fromCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='market.currency'),
        ),
        migrations.AlterField(
            model_name='tradecurrency',
            name='toCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='market.currency'),
        ),
        migrations.DeleteModel(
            name='TradeFiatCurrency',
        ),
        migrations.DeleteModel(
            name='TradeCryptoCurrency',
        ),
    ]
