# Generated by Django 5.1.6 on 2025-04-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_currency_alter_tradecurrency_fromcurrency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotbalance',
            name='available_balance',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='spotbalance',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='spotbalance',
            name='total_balance',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
