# Generated by Django 5.1.6 on 2025-04-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_rename_order_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
