# Generated by Django 5.1.6 on 2025-04-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_delete_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.DecimalField(decimal_places=8, default=0, max_digits=50)),
                ('coin_price', models.DecimalField(decimal_places=8, default=0, max_digits=50)),
                ('order_type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=10)),
                ('market_type', models.CharField(choices=[('SPOT', 'spot'), ('FUTURES', 'futures')], max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
